/* ═══════════════════════════════════════════════════════════════
   TRADEBABY PRO v10 — COMPREHENSIVE QUIZ BANK
   200+ multiple choice questions across all trading subjects
   ═══════════════════════════════════════════════════════════════ */

const QUIZ_BANK = {
  forex_basics: [
    {q:"What is the daily trading volume of the forex market?", opts:["$750 billion","$7.5 trillion","$75 trillion","$750 trillion"], correct:1, explanation:"The forex market trades approximately $7.5 trillion daily, making it the largest and most liquid financial market in the world — 50x larger than all global stock markets combined."},
    {q:"In the currency pair EUR/USD, which is the base currency?", opts:["USD","EUR","Both","Neither"], correct:1, explanation:"The base currency is always the first listed currency. In EUR/USD, EUR (Euro) is the base currency. The price shows how many USD are needed to buy 1 EUR."},
    {q:"What does a pip represent in EUR/USD?", opts:["0.01","0.001","0.0001","0.00001"], correct:2, explanation:"For most pairs including EUR/USD, 1 pip = 0.0001 (the 4th decimal place). JPY pairs are different: 1 pip = 0.01 (2nd decimal place)."},
    {q:"How many currency units are in a standard lot?", opts:["1,000","10,000","100,000","1,000,000"], correct:2, explanation:"A standard lot = 100,000 currency units. A mini lot = 10,000. A micro lot = 1,000. Most beginners start with micro lots."},
    {q:"What is the approximate pip value for a mini lot on EUR/USD?", opts:["$10","$1","$0.10","$100"], correct:1, explanation:"Mini lot (10,000 units) on EUR/USD = approximately $1 per pip. Standard lot = $10/pip. Micro lot = $0.10/pip."},
    {q:"When does the London/New York overlap session occur?", opts:["08:00-12:00 UTC","13:00-17:00 UTC","00:00-04:00 UTC","20:00-00:00 UTC"], correct:1, explanation:"The London/NY overlap (13:00-17:00 UTC) is the most active trading window of the day. Both major financial centers are simultaneously active, creating highest volume and tightest spreads."},
    {q:"What does 'going long' EUR/USD mean?", opts:["Selling euros","Buying euros and selling dollars","Selling dollars only","Buying dollars"], correct:1, explanation:"Going long EUR/USD means buying the base currency (EUR) while simultaneously selling the quote currency (USD). You profit if EUR strengthens against USD."},
    {q:"What is the spread in forex?", opts:["The daily price range","The difference between bid and ask","The overnight interest","The commission charged"], correct:1, explanation:"The spread is the difference between the bid (sell) price and the ask (buy) price. It is the broker's built-in fee on every trade. You always buy at ask (higher) and sell at bid (lower)."},
    {q:"Which pair would be considered an 'exotic pair'?", opts:["EUR/USD","GBP/JPY","USD/ZAR","AUD/NZD"], correct:2, explanation:"USD/ZAR (US Dollar/South African Rand) is an exotic pair — one major currency paired with an emerging market currency. Exotic pairs have wider spreads and lower liquidity than major or cross pairs."},
    {q:"What is leverage in forex trading?", opts:["A type of currency pair","Borrowing from broker to control larger position","The daily pip range","Commission on trades"], correct:1, explanation:"Leverage allows you to control a position larger than your deposit. 100:1 leverage means $1,000 controls $100,000. It amplifies both profits AND losses equally."},
    {q:"With 100:1 leverage and $2,000 deposit, what position can you control?", opts:["$2,000","$20,000","$200,000","$2,000,000"], correct:2, explanation:"100:1 leverage × $2,000 deposit = $200,000 position. This means a 1% adverse move would wipe out your entire $2,000 deposit. Always use leverage cautiously."},
    {q:"What is a margin call?", opts:["A request to add more trades","Broker warning when equity falls below required margin","A profitable trade signal","The spread during news events"], correct:1, explanation:"A margin call occurs when your account equity falls below the required margin level (typically 100%). The broker warns you to deposit more funds or close positions to prevent stop-out."},
    {q:"Which session has the highest forex trading volume?", opts:["Asian session","London session","New York session","Sydney session"], correct:1, explanation:"The London session (08:00-17:00 UTC) handles approximately 35% of global forex volume — the largest of any single session. London is the world's largest forex trading center."},
    {q:"What does NFP stand for in forex?", opts:["Net Forex Profit","Non-Farm Payrolls","Normal Foreign Position","New Fund Policy"], correct:1, explanation:"NFP = Non-Farm Payrolls. Released first Friday of every month by the US Bureau of Labor Statistics. It's the number of jobs created outside agriculture. The biggest regular USD mover."},
    {q:"What is a cross currency pair?", opts:["Any pair including USD","A pair not involving USD","Two pairs traded simultaneously","A pair traded on an exchange"], correct:1, explanation:"A cross (or minor) pair does not include the US Dollar. Examples: EUR/GBP, EUR/JPY, GBP/JPY. These pairs have slightly wider spreads than major USD pairs."},
  ],
  
  technical_analysis: [
    {q:"What is the golden cross in moving average analysis?", opts:["Price touching MA200","50 MA crossing above 200 MA","9 MA crossing 21 MA","Price breaking resistance"], correct:1, explanation:"The Golden Cross occurs when the 50-period MA crosses ABOVE the 200-period MA. It signals a potential long-term bullish trend change and is one of the most widely watched signals by institutional traders."},
    {q:"RSI stands for:", opts:["Relative Strength Indicator","Relative Strength Index","Rate of Strength Indicator","Relative Speed Index"], correct:1, explanation:"RSI = Relative Strength Index. Created by J. Welles Wilder in 1978. Measures momentum on a 0-100 scale. Above 70 = overbought, below 30 = oversold, 50 = trend filter."},
    {q:"What does an RSI reading above 70 typically indicate?", opts:["Strong buy signal","Overbought conditions — potential reversal","Strong downtrend","Breakout confirmed"], correct:1, explanation:"RSI above 70 indicates overbought conditions — the asset may have risen too far too fast and could be due for a pullback. However, in strong trends RSI can remain above 70 for extended periods."},
    {q:"What is a bearish divergence?", opts:["Price falls while RSI rises","Price makes new high but RSI makes lower high","Both price and RSI fall together","RSI above 70 during uptrend"], correct:1, explanation:"Bearish divergence: Price makes a new HIGH but the momentum indicator (RSI/MACD) makes a LOWER high. This shows weakening upside momentum despite the price continuing higher — a warning of potential reversal."},
    {q:"What does Bollinger Band Squeeze indicate?", opts:["High volatility period","Overbought market","Low volatility — big move likely incoming","Strong trend continuation"], correct:2, explanation:"Bollinger Band Squeeze occurs when the upper and lower bands converge (narrow). This indicates a period of very low volatility. Low volatility periods are typically followed by high volatility breakouts."},
    {q:"What is a support level?", opts:["Area where price always stops rising","Price zone where buyers historically overcome sellers","Random price point","Always the 200-day moving average"], correct:1, explanation:"A support level is a price zone where buying interest has historically overcome selling pressure, causing price to bounce higher. More touches without breaking = stronger support."},
    {q:"What happens when broken support is retested?", opts:["It becomes stronger support","It usually becomes resistance (role reversal)","It disappears permanently","Price always breaks through again"], correct:1, explanation:"Role Reversal: When support is broken decisively, it typically becomes resistance when retested from below. This is one of the highest-probability setups in technical analysis."},
    {q:"What is an uptrend defined by?", opts:["Higher highs only","Lower lows only","Series of higher highs AND higher lows","Price above the 50 MA"], correct:2, explanation:"An uptrend is defined by a series of Higher Highs (HH) AND Higher Lows (HL). Each peak is higher than the last AND each trough is higher than the last. Both conditions must be present."},
    {q:"What is the MACD histogram?", opts:["MACD line minus the signal line","The 26 EMA","Average of fast and slow EMA","RSI applied to MACD"], correct:0, explanation:"The MACD histogram = MACD Line minus Signal Line. It visually shows momentum strength and direction. When histogram is growing = momentum increasing. When shrinking = momentum weakening."},
    {q:"What is the 'golden pocket' in Fibonacci?", opts:["The 50% level","The 38.2% level","The 61.8% level","The 23.6% level"], correct:2, explanation:"The 61.8% Fibonacci level is called the Golden Pocket or Golden Ratio. It is the most respected retracement level globally and where the largest concentration of institutional orders typically cluster."},
    {q:"What minimum number of touches confirms a strong S&R level?", opts:["1 touch","2 touches","3 or more touches","10 touches"], correct:2, explanation:"While 2 touches confirm a level exists, 3 or more touches make it a highly significant level. Each time price respects a level and reverses, it confirms more buying or selling interest is present there."},
    {q:"Which candlestick pattern represents 'maximum bearish conviction'?", opts:["Hammer","Bearish Marubozu","Shooting Star","Doji"], correct:1, explanation:"A Bearish Marubozu is a full-body candle with no wicks where the open = high and the close = low. It shows that sellers controlled the entire period with no pushback from buyers whatsoever."},
    {q:"What is the minimum wick-to-body ratio for a valid Pin Bar?", opts:["1:1 ratio","2:1 wick to body","The wick must be longer than the body","Any wick qualifies"], correct:1, explanation:"A valid pin bar requires the wick to be at least 2× the length of the body. The small body should be at one end (near the high or low). Context is everything — the setup location matters more than the exact ratio."},
    {q:"What does ATR measure?", opts:["Average trend ratio","Average true range — market volatility","Asset trading revenue","Automatic trend recognition"], correct:1, explanation:"ATR (Average True Range) measures market volatility by calculating the average of the true range (largest of: High-Low, |High-Prev Close|, |Low-Prev Close|) over n periods. Higher ATR = more volatile market."},
    {q:"In Elliott Wave Theory, which wave is NEVER the shortest?", opts:["Wave 1","Wave 2","Wave 3","Wave 4"], correct:2, explanation:"One of the three inviolable Elliott Wave rules: Wave 3 is NEVER the shortest of waves 1, 3, and 5. Wave 3 is typically the longest and strongest wave. Breaking this rule means your wave count is wrong."},
  ],
  
  risk_management: [
    {q:"What is the maximum recommended risk per trade for beginners?", opts:["5-10%","10-15%","1-2%","25%"], correct:2, explanation:"The 1-2% rule: never risk more than 1-2% of your account on any single trade. This allows you to survive 50+ consecutive losses without blowing your account. It is the single most important rule in trading."},
    {q:"After a 50% account loss, what return is needed to recover?", opts:["50% return","75% return","100% return","25% return"], correct:2, explanation:"The mathematics of drawdown recovery: if you lose 50% (from $10,000 to $5,000), you need a 100% return on the remaining $5,000 just to get back to $10,000. This is why preventing large drawdowns is critical."},
    {q:"With 1:2 R:R, what minimum win rate is needed to profit?", opts:["50%","40%","34%","60%"], correct:2, explanation:"Break-even win rate = 1 / (1 + R:R). For 1:2 R:R: 1/(1+2) = 33.3%. This means you only need to win 34% of your trades to be profitable. This is why R:R ratio is more important than win rate alone."},
    {q:"What is the profit factor formula?", opts:["Total trades / Winners","Gross profit / Gross loss","Average win / Average loss","Wins / Total trades"], correct:1, explanation:"Profit Factor = Gross Profit ÷ Gross Loss. A profit factor above 1.0 = profitable system. Above 1.3 = good. Above 1.5 = excellent. Below 1.0 = losing money overall."},
    {q:"What is expectancy in trading?", opts:["How long you expect a trade to last","Expected profit per dollar risked over many trades","The success rate of your strategy","Maximum loss on any one trade"], correct:1, explanation:"Expectancy = (Win% × Avg Win) − (Loss% × Avg Loss). It represents the average profit per dollar risked over many trades. Positive expectancy = profitable edge. The foundation of every viable strategy."},
    {q:"After 20 consecutive losses at 5% risk per trade, your account is approximately:", opts:["Down 20%","Down 35%","Down 64%","Down 100%"], correct:2, explanation:"Compound math: 0.95^20 = 0.358. So you'd have 35.8% of your original account — a 64.2% drawdown. To recover from -64% requires a +178% return. This illustrates why the 1-2% rule is survival math."},
    {q:"What should you do immediately after 3 consecutive losses?", opts:["Increase position size to recover","Continue trading with same size","Stop trading for the day","Switch to a different strategy"], correct:1, explanation:"After 3 consecutive losses, the professional response is to stop trading for the day. Take a break, review the trades in your journal, and return fresh tomorrow. Never increase size to recover — this creates account-destroying cascades."},
    {q:"The ATR-based stop loss formula is:", opts:["SL = Entry ± 50 pips","SL = Entry ± (1.5 × ATR)","SL = Entry ± (Average R:R)","SL = Entry ± (Account × 1%)"], correct:1, explanation:"ATR-based stops: SL = Entry price ± (1.5 to 2 × ATR14). This automatically adjusts your stop to market volatility — wider in volatile markets, tighter in calm ones. Much smarter than fixed pip stops."},
    {q:"What is 'heat' in trading portfolio context?", opts:["Emotional state while trading","Total open risk across all positions","Daily P&L result","Temperature of the market"], correct:1, explanation:"Heat = total open risk across all your current positions simultaneously. If you have 3 trades each risking 1%, your total heat is 3%. Professional traders manage total portfolio heat (typically 3-6% maximum) not just per-trade risk."},
    {q:"What is the Kelly Criterion used for?", opts:["Measuring chart patterns","Optimal position sizing based on win rate and R:R","Calculating spread costs","Identifying trend direction"], correct:1, explanation:"The Kelly Criterion provides a formula for optimal position sizing: f* = (bp - q) / b where b=odds, p=win probability, q=loss probability. Most professionals use Quarter-Kelly (25% of full Kelly) to reduce drawdowns while maintaining edge."},
  ],
  
  psychology: [
    {q:"What is loss aversion in trading psychology?", opts:["Avoiding all trades with potential losses","Losses feel approximately 2-2.5x more painful than equivalent gains feel good","Only trading profitable strategies","Setting very wide stop losses"], correct:1, explanation:"Loss aversion: psychologically, losses hurt approximately 2-2.5x more than equivalent gains feel good. This causes traders to hold losers too long (avoiding the pain) and cut winners too early (locking in gain before it disappears)."},
    {q:"What is the Gambler's Fallacy in trading?", opts:["Thinking you are always right","Believing past independent trades affect future probability","Trading too many positions","Using leverage too high"], correct:1, explanation:"Gambler's Fallacy: believing that past independent events influence future independent events. Example: 'I've lost 5 trades in a row so I'm due a win.' Each trade is statistically independent — past results don't change future probability."},
    {q:"What is the sunk cost fallacy in trading?", opts:["Paying too much in commissions","Holding a losing trade because of time/money already invested","Trading during news events","Using too much leverage"], correct:1, explanation:"Sunk Cost Fallacy: continuing to hold a position because of investment already made, rather than future expected value. 'I cannot close this losing trade after holding it 3 days.' Past investment is irrelevant to current decisions."},
    {q:"What is revenge trading?", opts:["Trading with aggressive strategies","Re-entering trades immediately after losses to quickly recover","Using very large position sizes","Trading during news events"], correct:1, explanation:"Revenge trading: entering new trades driven by the emotional need to recover a recent loss, not by a valid setup. The single biggest account destroyer. The response should always be: stop trading, review, return tomorrow."},
    {q:"What is confirmation bias?", opts:["Confirming each trade with multiple indicators","Only seeking information that confirms your existing beliefs","Waiting for price confirmation before entering","Using trade confirmation emails"], correct:1, explanation:"Confirmation Bias: the tendency to search for and interpret information that confirms pre-existing beliefs while ignoring contradicting evidence. In trading: only seeing the bullish signs when you want to go long."},
    {q:"What does 'process-oriented trading' mean?", opts:["Using automated trading systems","Judging trades on rule-following, not outcomes","Trading with a set process each morning","Only trading certain setups"], correct:1, explanation:"Process-oriented trading means judging each trade on whether you followed your rules — not on whether it won or lost. A perfectly executed losing trade is a success. A rule-breaking winning trade is a failure. This mindset builds consistency."},
    {q:"What is FOMO in trading?", opts:["Forex Official Market Order","Fear Of Missing Out — entering late due to anxiety of missing a move","A type of indicator","Moving average crossover"], correct:1, explanation:"FOMO (Fear Of Missing Out): the anxiety that causes traders to enter after a move has already happened, afraid of missing further gains. Creates late entries with poor R:R. Accept that missed trades are free — bad FOMO trades cost money."},
    {q:"What is 'overconfidence bias' in trading?", opts:["Being confident in your analysis","Excessive confidence after a winning streak leading to oversizing or rule-breaking","Confidence in your broker","Trading only setups you understand"], correct:1, explanation:"Overconfidence Bias: excessive belief in one's own predictions and abilities, usually following a winning streak. Manifests as taking lower-quality setups, increasing size recklessly, or abandoning risk management. Win streaks are the most dangerous periods."},
    {q:"What is Mark Douglas known for in trading education?", opts:["Inventing the RSI indicator","Creating the MACD","Writing Trading in the Zone — the psychology bible","Founding the Chicago Board of Trade"], correct:2, explanation:"Mark Douglas wrote 'Trading in the Zone' (2000) and 'The Disciplined Trader' (1990) — the two most influential books on trading psychology. His concept of 'probabilistic thinking' and accepting uncertainty fundamentally changed how traders think about consistency."},
    {q:"What is 'flow state' in trading?", opts:["Analyzing market flow","Complete absorption in trading with optimal performance — no emotional interference","When all indicators point the same direction","Market condition with strong trend"], correct:1, explanation:"Flow State (Csikszentmihalyi): complete immersion in an activity where execution feels effortless and automatic. Athletes call it 'the zone.' In trading, flow comes from thorough preparation, clear rules, and emotional acceptance of uncertainty."},
  ],
  
  fundamental: [
    {q:"What does 'hawkish' mean for a central bank?", opts:["Favoring rate cuts","Favoring rate hikes and tighter money supply","Aggressive trading style","Neutral monetary policy"], correct:1, explanation:"Hawkish: a central bank stance favoring higher interest rates or tighter monetary policy to control inflation. Hawkish signals typically strengthen the currency as higher rates attract capital inflows from foreign investors."},
    {q:"What does 'dovish' mean for a central bank?", opts:["Favoring rate hikes","Favoring rate cuts and loose money supply","Neutral stance","Aggressive intervention"], correct:1, explanation:"Dovish: a central bank stance favoring lower interest rates or looser monetary policy to stimulate economic growth. Dovish signals typically weaken the currency as lower rates reduce investment attractiveness."},
    {q:"What does CPI measure?", opts:["Currency price index","Consumer price index — measures inflation","Central policy indicator","Credit payment index"], correct:1, explanation:"CPI (Consumer Price Index) measures the average change in prices paid by consumers for a basket of goods and services. It is the primary inflation measure. Central banks target 2% CPI. Higher CPI = rate hike pressure = currency strength."},
    {q:"When does NFP typically cause the biggest market movements?", opts:["When the number is as expected","When the actual number is significantly different from forecast","Only when unemployment also changes","During Asian trading hours"], correct:1, explanation:"Markets price in EXPECTATIONS. NFP moves markets most when the actual number deviates significantly from the forecast (consensus expectation). A large beat = USD strength. A large miss = USD weakness. The surprise IS the move."},
    {q:"Interest rate differentials primarily affect currency values through:", opts:["Technical support and resistance","Capital flows toward higher-yielding currencies","Chart pattern formation","Central bank intervention only"], correct:1, explanation:"Interest rate differentials drive capital flows. Investors and institutions move money to where it earns the most return. Higher rates = more attractive = currency demand increases = currency strengthens. This is the most powerful long-term forex driver."},
    {q:"What is quantitative easing (QE)?", opts:["Measuring exactly how much to trade","Central bank buying assets to inject money into economy","Bank lending program for retail clients","Forex volume analysis technique"], correct:1, explanation:"QE: a central bank creates new money and uses it to buy government bonds or other assets, injecting liquidity into the economy. Expansionary policy. Generally weakens the currency as it increases the money supply. First widely used in 2008 by the Fed."},
    {q:"What is 'risk on' in forex context?", opts:["High position sizing","Market sentiment favoring risky assets — investors sell USD/JPY/CHF, buy AUD/NZD","Trading without stops","News trading strategy"], correct:1, explanation:"Risk-on: market sentiment where investors are confident, buying risky assets (equities, high-yield currencies like AUD, NZD). Safe-haven currencies (USD, JPY, CHF) and gold typically weaken. Opposite is risk-off (fear = safety buying)."},
    {q:"Which economic indicator is considered a 'leading indicator'?", opts:["GDP (backward-looking)","CPI (monthly)","PMI (Purchasing Managers Index)","Unemployment rate (lagging)"], correct:2, explanation:"PMI is a leading indicator because purchasing managers ORDER goods and materials ahead of production. When PMI is rising, it signals economic expansion before it shows in GDP or employment data. Above 50 = expansion, below 50 = contraction."},
    {q:"What drives the Canadian Dollar (CAD) most strongly?", opts:["Bank of Canada speeches only","WTI Crude Oil prices (negative correlation with USD/CAD)","Canadian housing data","US stock market performance"], correct:1, explanation:"The Canadian Dollar is strongly correlated with WTI crude oil prices. Canada is a major oil exporter. When oil prices rise, CAD strengthens (USD/CAD falls). When oil falls, CAD weakens (USD/CAD rises). Oil is the #1 fundamental driver for CAD."},
    {q:"What causes a 'carry trade unwind'?", opts:["Broker changing swap rates","Risk-off events cause rapid exit of carry positions, often creating violent moves","Central bank lowering rates gradually","NFP data release"], correct:1, explanation:"Carry trade unwind: when global risk-off events cause carry traders to rapidly exit their positions simultaneously. Example: AUD/JPY falls sharply as traders sell AUD (high yield) and buy JPY (low yield) all at once. Unwinds can be 10-30% moves in days."},
  ],
  
  smc_advanced: [
    {q:"What is a Bullish Order Block in SMC?", opts:["Any bullish candle on the chart","The last bearish candle before a significant bullish impulse move","A cluster of buy orders","The highest point before a reversal"], correct:1, explanation:"Bullish Order Block: the last BEARISH candle before a significant bullish impulse that creates a Break of Structure. This candle represents where smart money (institutions) was building their long positions. Price returns here for institution to fill remaining orders."},
    {q:"What is a Fair Value Gap (FVG)?", opts:["A gap in the daily chart","A 3-candle pattern where candle 1 and candle 3 don't overlap, leaving untraded prices","The difference between bid and ask","A gap at market open"], correct:1, explanation:"FVG (Fair Value Gap): a 3-candle imbalance where the first and third candle don't overlap, creating an area of untraded prices. Represents an imbalance of orders. Price tends to return to 'fill' the FVG before continuing the original direction."},
    {q:"What does CHOCH stand for?", opts:["Change of Character — first structure break against the prevailing trend","Chart Order Confirmation High","Change of Chart Analysis","Currency Hedge Order Change"], correct:0, explanation:"CHOCH = Change of Character. It is the first candle that breaks structure AGAINST the prevailing trend direction. In an uptrend, the CHOCH breaks the most recent Higher Low. This is the first warning that the trend may be reversing."},
    {q:"What is the difference between BOS and CHOCH?", opts:["No difference, same concept","BOS confirms trend continuation; CHOCH signals potential reversal","BOS is bearish; CHOCH is bullish","BOS is on H4; CHOCH is on H1"], correct:1, explanation:"BOS (Break of Structure) = price breaks in the SAME direction as the trend = trend continuation signal. CHOCH (Change of Character) = price breaks AGAINST the trend direction = potential reversal warning. Both are structural concepts."},
    {q:"In SMC, what is the 'premium zone'?", opts:["High-quality Order Block","Price above the 50% level of a recent swing range — expensive","A special account type","Best pair for trading"], correct:1, explanation:"Premium zone: price above the 50% midpoint of the most recent swing range. In SMC, you should SELL in premium (price is expensive). DISCOUNT zone is below 50% — you should BUY there (price is cheap). This filter eliminates many bad entries."},
    {q:"What makes an Order Block 'fresh'?", opts:["It was created today","It has never been previously tested (retested) by price","It is above the current price","It has a Fair Value Gap"], correct:1, explanation:"A fresh Order Block has never been retested (price has not returned to it since the impulse move). Fresh OBs have the highest probability because institutions haven't filled all their remaining orders yet. OBs tested twice+ are significantly weakened."},
    {q:"What are 'equal highs/lows' in SMC?", opts:["Symmetrical chart patterns","Price levels where two or more candles have nearly identical highs or lows — liquidity pools","Support and resistance zones","Elliott Wave levels"], correct:1, explanation:"Equal Highs/Lows in SMC = liquidity pools. When price makes two or more touches at the same high or low, retail traders cluster stops there. Institutions hunt this liquidity before reversing. Equal highs/lows are TARGETS, not levels to trade against."},
    {q:"What is 'displacement' in SMC?", opts:["Broker slippage","A large, fast candle that breaks structure and creates a Fair Value Gap","Moving to a new chart timeframe","Price retracing to an Order Block"], correct:1, explanation:"Displacement: a large, impulsive candle that aggressively breaks through a key level, creating a Fair Value Gap in its wake. Shows decisive institutional participation. The FVG created by displacement is a high-probability reentry zone."},
    {q:"In the SMC entry model, what is the correct sequence?", opts:["FVG → CHOCH → OB entry","HTF trend → H1 CHOCH → OB identification → wait for retest → M15 entry","Enter at every Order Block regardless of context","Trade any CHOCH you see"], correct:1, explanation:"Correct SMC sequence: (1) Identify HTF (D1/H4) trend direction via BOS patterns. (2) Wait for H1 CHOCH against HTF trend. (3) Mark Order Block at the CHOCH. (4) Wait for price to return to OB. (5) M15 entry confirmation at OB zone."},
    {q:"What is 'mitigation' in SMC?", opts:["Reducing position size","Price returning to and using up the remaining orders at an Order Block","Adjusting stop loss","Moving to a safer market"], correct:1, explanation:"Mitigation: when price returns to an Order Block and fills the remaining institutional orders there. After full mitigation, the OB loses its significance. Partially mitigated OBs retain some validity. Fully mitigated OBs should not be traded again."},
  ],
};

// Add extended quiz bank to QUIZZES object if it exists
if (typeof QUIZZES !== 'undefined') {
  Object.assign(QUIZZES, QUIZ_BANK);
}

// Count total questions
const totalQuestions = Object.values(QUIZ_BANK).reduce((sum, arr) => sum + arr.length, 0);
console.log('Quiz bank loaded: ' + totalQuestions + ' questions across ' + Object.keys(QUIZ_BANK).length + ' categories');
